repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: goimports
        name: goimports
        description: Run goimports on the repository
        entry: go tool goimports -local github.com/sumnerevans/webfortune -w .
        language: unsupported
        pass_filenames: false
        types: [ go ]
      - id: staticcheck
        name: staticcheck
        description: Run staticcheck on the repository
        entry: go tool staticcheck ./...
        language: unsupported
        pass_filenames: false
        types: [ go ]

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-vet-repo-mod

  - repo: https://github.com/beeper/pre-commit-go
    rev: v0.3.0
    hooks:
      - id: zerolog-ban-msgf
